apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      component: keycloak
  template:
    metadata:
      labels:
        component: keycloak
    spec:
      containers:
        - name: keycloak
          image: jboss/keycloak:8.0.1
          ports:
            - containerPort: 8080
          env:
            - name: KEYCLOAK_USER
              valueFrom:
                secretKeyRef:
                  name: keycloaksecret
                  key: KEYCLOAKUSER
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloaksecret
                  key: KEYCLOAKPASSWORD
            - name: DB_VENDOR
              value: postgres
            - name: DB_ADDR
              value: postgres-keycloak-cluster-ip-service
            - name: DB_PORT
              value: '5432'
            - name: DB_DATABASE
              value: keycloak
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: keycloaksecret
                  key: PGKEYCLOAKUSER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloaksecret
                  key: PGKEYCLOAKPASSWORD
