apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: consul-ui-ingress-route
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`consului.localhost`)
      kind: Rule
      services:
        - name: consul-branden-consul-ui
          namespace: default
          port: 80
      middlewares:
        - name: admin-auth
  tls:
    secretName: traefik-tls-secret

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: consul-ui-ingress-route-http
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`consului.localhost`)
      kind: Rule
      services:
        - name: consul-branden-consul-ui
          namespace: default
          port: 80
      middlewares:
        - name: https
        - name: admin-auth
