apiVersion: v1
kind: Service
metadata:
  name: grafana-operated
  labels:
    operated-grafana: 'true'

spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      name: web
      port: 3000
      targetPort: grafana
